name: big_bird
description: Библиотека для работы с документами
version: 0.0.1
homepage: https://github.com/Lonti6/big_bird

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.zhiltsov.big_bird
        pluginClass: BigBirdPlugin
      windows:
        pluginClass: BigBirdPluginCApi
      web:
        pluginClass: BigBirdWeb
        fileName: big_bird_web.dart
